### PR TITLE
adding Cyrillic and Vietnamese text samples (Goethe)

### PR DESCRIPTION
**Pull request by alexeiva**
Let this hang til it's done.

screen shot 2016-11-28 at 2 35 53 pm

**todo:** Make Cyrillic and Vietnamese tabs show/hide from the top menu.
Cyrillic isn't fetched form the GF API.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Ok awesome,

I don't mind a drop down bar where you can change the language. Like impallari/testings OT feature enable/disable

screen shot 2016-11-28 at 14 45 05

The languages available to the user must be present in the font. No arb languages :-)

**Comment by m4rc1e** [comment]
@alexeiva 

I've decided we need to see a paragraph of each language in the font, with correct html language tags enabled. Nototools has [this](https://github.com/googlei18n/nototools/blob/master/nototools/generate_sample_from_exemplar.py). 

I've been submitting Indic and Arabic fonts recently and have been relying on font dragr and bbc websites. This isn't good enough.


cc @davelab6

**Comment by m4rc1e** [comment]
@alexeiva 

Languages are now discovered if they have gsub features. I'm tempted to use codepoints instead, what do you think?

lang-processing


In order to get the sample text for each language. I've had to make a small db, repo [here](https://github.com/m4rc1e/iso639corpora)
cc @davelab6

**Comment by davelab6** [comment]
@m4rc1e you will need to PR font families with cyrillic, are you ready for this? :D

**Comment by davelab6** [comment]
@m4rc1e please put some time in your tracker for this

**Comment by davelab6** [comment]
@m4rc1e when do you plan to work on this?

**Comment by m4rc1e** [comment]
This paragraph proofing is a relic from the first release. I removed it almost a year ago. I initially used this view to test if the vertical metrics were in sync. Its been replaced by the waterfall view.

If a user would like to diff text samples, there's an editor to do this. Users can paste whatever text they like in there.

**Pull request closed without merging**
